export type AlgorithmType = 
  | 'bfs' 
  | 'dfs' 
  | 'dijkstra'
  | 'traverse'
  | 'reverse'
  | 'bubbleSort'
  | 'quickSort'
  | 'insertionSort'
  | 'selectionSort'
  | 'mergeSort'
  | 'createLinkedList'
  | 'searchLinkedList'
  | 'insertNode'
  | 'deleteNode'
  | 'create'
  | 'bstInsert'; // Added new algorithm type